version: '3'
services:

  master:
    build: ./jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-net

  gitrepo:
    build: ./gitrepo
    ports:
      - "2222:22"
    volumes:
      - ~/git-server/keys:/git-server/keys
      - ~/git-server/repos:/git-server/repos
    networks:
      - jenkins-net

  nexus:
    image: sonatype/nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/sonatype-work
    networks:
      - jenkins-net

  tomcat:
    image: tomcat:9.0
    ports:
      - "8888:8080"
    volumes:
      - tomcat-data:/usr/local/tomcat
    networks:
      - jenkins-net

  sonar:
    image: sonarqube:7.1
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - jenkins-net
 
  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    networks:
      - jenkins-net
  
  selenium-chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - jenkins-net
  
  selenium-firefox:
    image: selenium/node-firefox
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - jenkins-net
      

  slave:
    build: ./jenkins-slave
    networks:
      - jenkins-net

  proxy:
    build: ./docker-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      jenkins-net:
        aliases:
          - proxy1

volumes:
  jenkins-log:
  jenkins-data:
  nexus-data:
  tomcat-data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:

networks:
  jenkins-net:
