version: '3'
services:

  master:
    build: ./jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins-net
   
  slave:
    build: kacperos/devops-slave
    networks:
      - jenkins-net
    deploy:
      mode: replicated
      replicas: 2

  proxy:
    build: ./docker-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      jenkins-net:
        aliases:
          - proxy1

volumes:
  jenkins-log:
  jenkins-data:

networks:
  jenkins-net:
