version: "3"
services:
  nginx:
    # replace username/repo:tag with your name and image details
#    image: kacperos/get-started:part1
    image: localhost:5000/nginx 
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8383:80"
    networks:
      - nginx_net
networks:
  nginx_net:

