version: '3'
services:
  gitek:
    build: .
    restart: unless-stoped
    ports:
      - "2223:22"
    volumes:
      - ~/git-server/keys:/git-server/keys
      - ~/git-server/repos:/git-server/repos
